// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAodfO9382neMkUwi0IJq2meimikHy6RYk',
    appId: '1:401538334141:web:b8ea4d22bd730278ada6d4',
    messagingSenderId: '401538334141',
    projectId: 'mini-messenger-app-6ec28',
    authDomain: 'mini-messenger-app-6ec28.firebaseapp.com',
    storageBucket: 'mini-messenger-app-6ec28.firebasestorage.app',
    measurementId: 'G-BZ04S183TF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3-PUWMnQ4zas7KVkYoFOsh1v9PFVyddY',
    appId: '1:401538334141:android:37c7b6ce6f388e53ada6d4',
    messagingSenderId: '401538334141',
    projectId: 'mini-messenger-app-6ec28',
    storageBucket: 'mini-messenger-app-6ec28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3sF63cpA_XEhx2bTgBtWnQX88ENT8Oi0',
    appId: '1:401538334141:ios:92f84f7d8aec41f6ada6d4',
    messagingSenderId: '401538334141',
    projectId: 'mini-messenger-app-6ec28',
    storageBucket: 'mini-messenger-app-6ec28.firebasestorage.app',
    iosClientId: '401538334141-u7opdrj6e68aje3urkbs3g3ne6fpambi.apps.googleusercontent.com',
    iosBundleId: 'com.example.messengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3sF63cpA_XEhx2bTgBtWnQX88ENT8Oi0',
    appId: '1:401538334141:ios:92f84f7d8aec41f6ada6d4',
    messagingSenderId: '401538334141',
    projectId: 'mini-messenger-app-6ec28',
    storageBucket: 'mini-messenger-app-6ec28.firebasestorage.app',
    iosClientId: '401538334141-u7opdrj6e68aje3urkbs3g3ne6fpambi.apps.googleusercontent.com',
    iosBundleId: 'com.example.messengerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAodfO9382neMkUwi0IJq2meimikHy6RYk',
    appId: '1:401538334141:web:f1e47ff1629648ebada6d4',
    messagingSenderId: '401538334141',
    projectId: 'mini-messenger-app-6ec28',
    authDomain: 'mini-messenger-app-6ec28.firebaseapp.com',
    storageBucket: 'mini-messenger-app-6ec28.firebasestorage.app',
    measurementId: 'G-97WP3PTDY1',
  );
}
